### ISSUE TITLE
Why is PDF to image conversion default?

### ISSUE THREAD

**Issue by ogencoglu** [FeatureBaseDB/DoctorGPT#5]
Why are PDFs converted to images by default (according to README)? Most PDFs have embedded text and one does not need OCR or any image recognition to retrieve the text.

**Comment by kordless** [comment]
Most PDFs do have embedded text, but not all of them do. This code could easily be converted to use embedded results from the PDF, but I think I prefer to have a reliable means to extract text from ALL PDFs.

Did you get this running?

**Comment by ogencoglu** [comment]
> I prefer to have a reliable means to extract text from ALL PDFs.

OCR is not reliable at all.

I have solved my issue with other tools so I will be closing this.
